### PR TITLE
chore: add MAINTAINERS

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Review by avishnu — APPROVED** [review]

**Review by edrob999 — CHANGES_REQUESTED** [review]
1. Please replace lines 3-6 with this rewording:
\# OpenEBS is an umbrella project, composed as a federation of individual sub projects (repositories).
\# THIS MAINTAINERS FILE APPLIES TO THE UMBRELLA PROJECT, EVERY SUB-PROJECT, REPOSITORY  AND FILE IN THE OPENEBS ORGANIZATION. 
\# THIS MAINTAINERS FILE SUPERSEDES AND OVERRIDES ALL OTHER MAINTAINERS FILES.
2. Remove 2 files: maintainers, maintainers.old from openebs/openebs repo

**Review by orville-wright — COMMENTED** [review]
New file location is correct

1. Wording may be slightly off as Ed has some specific language for this file. Please check with his review.

2. Need to delete the original MAINTAINERS and MAINTAINERS_OLD files from openebs/openebs parent repo as Ed's strategy is to only have 1 instance of MAINTAINERS file across the entire org, project and all repos. 

3. Not sure if the deletion will be done in a separate PR ? 

4. All instances of MAINTAINERS files needs to be deleted when this file goes live.

**Review by orville-wright — APPROVED** [review]
Approved based on suggested changes

**Review by dave-brace — APPROVED** [review]
Approved based on suggest language changes and deletion of all other instances of MAINTAINERS doc across all locations in the ORG

**Review by tiagolobocastro — COMMENTED** [review]
@edrob999, updated PTAL

Also should we include email addresses as well

**Comment by edrob999** [comment]
signed-off-by: Ed Robinson <ed.robinson@gmail.com>

**Pull request merged**
